package miniheros.hero;

public enum Classes {

	// normal
	MENSCH, KRIEGER, MAGIER, ELF, ORK, GNOM, ZWERG, ZOMBIE, DRACHE, EISDRACHE,


	// STRANGE
	JESUS, GOTT, SATAN, HITLER, TEEKANNE, TEEBEUTEL, TOPF, COOLMAN,

	// SPECIAL
	NEINHEIT, JAHEIT, LEVIATHAN, ULTIMATEFORM,

	// MEDIA
	SHELDON, PENNY, LENNARD, GOKU, SPIDERMAN, DARKSPIDERMAN, SPIDERPIG, CREEPER;



}