package miniheros.hero;

public enum Spellz {

	// normal
    NORMAL, GESCHICKT, INTELLIGENT, MAGISCH,
    
    // KRIEGER
    ANSTURM, FURY,
    
    // ZOMBIE
    ZOMBIESCHLAG, HIRNWURF, ZOMBIERUF, ZOMBIEBISS,
    
    // DRACHE
    FEUERATEM, DRACHENSCHREI, FEUERBOMBE, DRACHENBISS
}
