package HeroPack;

public enum Classes {

    // normal
    MENSCH, KRIEGER, ELF, ORK, GNOM, ZWERG, MAGIER, ZOMBIE, DRACHE, EISDRACHE,
    // STRANGE
    JESUS, GOTT, SATAN, HITLER,
    // SPECIAL
    NEINHEIT, JAHEIT, LEVIATHAN, ULTIMATEFORM,
    // MEDIA CELEBS
    SHELDON, PENNY, LENNARD, GOKU, SPIDERMAN, DARKSPIDERMAN, SPIDERPIG;

}
